-- ============================================
-- Fuzzy Factory | Maven Analytics
-- Table: funnel_analysis
-- Description: Session-level funnel flags
-- per step aggregated by source, campaign,
-- device, and date for funnel dashboard
-- ============================================
